name: Auto approve and merge PRs by dependabot

# Trigger the workflow on pull request
on:
  pull_request

jobs:
  if: "contains(github.event.head_commit.message, 'chore(release)')"
 
  autoapprove:
    name: Auto Approve a PR by dependabot # Name of the job
    runs-on: ubuntu-latest # Environment on which the job runs
    
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v2.0.0
        with:
          github-token: ${{ secrets.APPROVE_TOKEN }}
  
  automerge:
    name: Auto merge after successful checks
    needs: autoapprove
    runs-on: ubuntu-latest

    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: automerge

      - name: Auto merge
        uses: pascalgn/automerge-action@v0.13.0
        env:
          GITHUB_TOKEN: ${{ secrets.APPROVE_TOKEN }}
