name: bump-version

on:
  pull_request_review:
    types: [submitted]
    branches: [ master, main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_12.3.app/Contents/Developer

jobs:
  bump-version:
    if: github.event.review.state == 'approved' && !contains(github.event.head_commit.message, 'chore(release)')
    
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch all tags
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        

    - name: Bump version
      run: |
        npx standard-version -t ''
        echo "RELEASE_VERSION=$(git describe --abbrev=0 | tr -d '\n')" >> $GITHUB_ENV
        export VERSION="$(git describe --abbrev=0 | tr -d '\n')"
        find . -name '*.podspec' | xargs -I% npx podspec-bump -i $VERSION -w -p %
        git add -A
        git commit --amend --no-edit

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.event.pull_request.head.ref }}
