name: merge

on:
  pull_request:
    branches: [ master, main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_12.3.app/Contents/Developer

jobs:
  merge:
    if: contains(github.event.head_commit.message, 'chore(release)')
    
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Auto approve
      uses: hmarr/auto-approve-action@v2.0.0
      with:
        github-token: ${{ secrets.APPROVE_TOKEN }}
