name: release

on:
  push:
    branches: [ master, main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_12.3.app/Contents/Developer

jobs:
  create-release:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2  
      with:
        token: ${{ secrets.RELEASE_TOKEN }}

    - name: Fetch all tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: Bump version
      run: |
        npx standard-version -t ''
        echo "$(git show-ref --tags)"
        echo "RELEASE_VERSION=$(git describe --abbrev=0 | tr -d '\n')" >> $GITHUB_ENV
        export VERSION="$(git describe --abbrev=0 | tr -d '\n')"
        find . -name '*.podspec' | xargs -I% npx podspec-bump -i "0.12.0" -w -p %
        git add -A
        git commit --amend --no-edit
        echo "$(git show-ref --tags)"
  
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.RELEASE_TOKEN }}
        branch: ${{ github.ref }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.RELEASE_VERSION }}
        release_name: LeadKit ${{ env.RELEASE_VERSION }}
        draft: false
        prerelease: false

    - name: Deploy to Cocoapods
      run: |
        set -euo pipefail
        pod repo add touchinstinct https://github.com/TouchInstinct/Podspecs
        find . -name '*.podspec' | xargs -I% pod repo push https://github.com/TouchInstinct/Podspecs % --allow-warnings
