name: release

on:
  push:
    branches: [ master, main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_12.3.app/Contents/Developer

jobs:
  create-release:
    if: "contains(github.event.head_commit.message, 'chore(release)')"

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2  
      with:
        token: ${{ secrets.RELEASE_TOKEN }}
        fetch-depth: 0

    - name: Fetch all tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: Create Release
      id: create_release
      uses: actions/create-release@main
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        tag_name: ${{ env.RELEASE_VERSION }}
        release_name: LeadKit ${{ env.RELEASE_VERSION }}
        draft: false
        prerelease: false
        commitish: ${{ github.ref }}

    - name: Deploy to Cocoapods
      run: |
        set -euo pipefail
        pod repo add touchinstinct https://github.com/TouchInstinct/Podspecs
        #find . -name '*.podspec' | xargs -I% pod repo push https://github.com/TouchInstinct/Podspecs % --allow-warnings
