name: release

on:
  push:
    branches: [ master, main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_12.3.app/Contents/Developer

jobs:
  create-release:
  
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2      

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts
        echo "$key" > ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa
        ssh-add
      env:
        key: ${{ secrets.SSH_KEY }}

    - name: Fetch all tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.RELEASE_VERSION }}
        release_name: LeadKit ${{ env.RELEASE_VERSION }}
        draft: false
        prerelease: false
